### ISSUE TITLE
请问有没有全部的文档呢

### ISSUE THREAD

**Issue by weiyanwei412** [arstercz/mha_manager_consul#1]
我在测试你的这个架构的时候，acl开启不了，能否给下你consul的配置文件

**Comment by arstercz** [comment]
抱歉这么久才回复. 具体配置可以参考我的博客说明 [mha and consul](https://arstercz.com/基于-consul-架构的-mha-自动切换/). acl  配置可以查看 consul 的[官方文档](https://www.consul.io/api/acl.html)
